spring:
  datasource:
    url: jdbc:mysql://47.110.39.144:9306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 'jxoa-2019_mt_oa'
  redis:
    host: 127.0.0.1
    port: 6379
    maxIdle: 200
    maxActive: 1024
    maxWait: 1000



staticPath: /data/wwwroot/biz/img/
server:
  port: 10010

